In [1]:
### ----- Imports ----- ###

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
import pandas as pd
import h5py
import time

In [2]:
### ----- Parameters ----- ###

# Where to save the products
models_figs_path = '/home/sdybing/mlaapde/figures/'

In [24]:
### ----- Load the MLAAPDE testing dataset from HDF5 files ----- ###

training_data = h5py.File('/hdd/mlaapde/decimated/training_data_full_decimate2.hdf5', 'r')
validation_data = h5py.File('/hdd/mlaapde/decimated/validation_data_full_decimate2.hdf5', 'r')
testing_data = h5py.File('/hdd/mlaapde/decimated/testing_data.hdf5', 'r')

datasetnames = training_data.keys()
print(datasetnames)

train_mags = training_data['magnitude'][:]
train_phase_id = training_data['phase_id'][:]
train_snrdb = training_data['snr_db'][:]

valid_mags = validation_data['magnitude'][:]
valid_phase_id = validation_data['phase_id'][:]
valid_snrdb = validation_data['snr_db'][:]

test_mags = testing_data['magnitude'][:]
test_phase_id = testing_data['phase_id'][:]
test_snrdb = testing_data['snr_db'][:]

<KeysViewHDF5 ['magnitude', 'magnitude_type', 'phase_id', 'snr_db', 'waves']>


In [25]:
training_data.close()
validation_data.close()
testing_data.close()

In [27]:
print(train_phase_id[0].decode())
print(train_phase_id[1])
print(train_phase_id[2])

usb000it1p_HL.ITM.HH*.--_P
b'usb000it1p_IM.MK31.BH*.--_P'
b'usb000it1p_KZ.ABKAR.BH*.--_P'


In [6]:
# Metadata to get distances for MLAAPDE data only - this file came from Hank and is for the ENTIRE MLAAPDE catalog

metadata = pd.read_csv('/home/sdybing/mlaapde/mlaapde_metadata.csv')
pd.set_option('display.max_columns', None)

/tmp/ipykernel_2351977/3367429034.py:3: DtypeWarning: Columns (38) have mixed types. Specify dtype option on import or set low_memory=False.
  metadata = pd.read_csv('/home/sdybing/mlaapde/mlaapde_metadata.csv')


In [7]:
len(train_mags) + len(valid_mags) + len(test_mags)

3244974

In [8]:
len(metadata)

5101567

In [9]:
metadata

Unnamed: 0                      phase_id                   waves_id   
0                 0   usc000irgm_GE.SNAA.BH*.--_P  usc000irgm_GE.SNAA.BH*.--  \
1                 1  usc000irgm_IU.PMSA.BH*.10_Sn  usc000irgm_IU.PMSA.BH*.10   
2                 2   usc000irgm_IU.QSPA.BH*.10_P  usc000irgm_IU.QSPA.BH*.10   
3                 3  usb000ikfk_AK.BPAW.BH*.--_Sn  usb000ikfk_AK.BPAW.BH*.--   
4                 4  usb000ikfk_AK.BRLK.BH*.--_Pn  usb000ikfk_AK.BRLK.BH*.--   
...             ...                           ...                        ...   
5101562     5101562   us6000d4ny_AV.RED.BH*.--_Sn   us6000d4ny_AV.RED.BH*.--   
5101563     5101563  us6000d4ny_IM.IL31.BH*.--_Pn  us6000d4ny_IM.IL31.BH*.--   
5101564     5101564  us6000d4ny_IU.COLA.HH*.00_Pn  us6000d4ny_IU.COLA.HH*.00   
5101565     5101565  us6000d4ny_TA.J18K.BH*.--_Pn  us6000d4ny_TA.J18K.BH*.--   
5101566     5101566  us6000d4ny_TA.M17K.BH*.--_Pn  us6000d4ny_TA.M17K.BH*.--   

           event_id       nscl_code network station channel location   
0        usc000irgm  GE.SNAA.BH*.--      GE    SNAA     BH*       --  \
1        usc000irgm  IU.PMSA.BH*.10      IU    PMSA     BH*       10   
2        usc000irgm  IU.QSPA.BH*.10      IU    QSPA     BH*       10   
3        usb000ikfk  AK.BPAW.BH*.--      AK    BPAW     BH*       --   
4        usb000ikfk  AK.BRLK.BH*.--      AK    BRLK     BH*       --   
...             ...             ...     ...     ...     ...      ...   
5101562  us6000d4ny   AV.RED.BH*.--      AV     RED     BH*       --   
5101563  us6000d4ny  IM.IL31.BH*.--      IM    IL31     BH*       --   
5101564  us6000d4ny  IU.COLA.HH*.00      IU    COLA     HH*       00   
5101565  us6000d4ny  TA.J18K.BH*.--      TA    J18K     BH*       --   
5101566  us6000d4ny  TA.M17K.BH*.--      TA    M17K     BH*       --   

         station_latitude  station_longitude  station_elevation_m   
0              -71.670700          -2.837900                846.0  \
1              -64.774400         -64.048900                 40.0   
2              -89.928900         144.438200               2850.0   
3               64.099701        -150.987305                619.0   
4               59.751100        -150.906300                409.0   
...                   ...                ...                  ...   
5101562         60.419600        -152.774200               1071.0   
5101563         64.771400        -146.886597                419.0   
5101564         64.873599        -147.861600                200.0   
5101565         63.465000        -156.715400                506.0   
5101566         61.400900        -157.437500                387.0   

        chan_order_3c  chan_azimuth_1  chan_azimuth_2  chan_azimuth_Z   
0                 ENZ            90.0             0.0             0.0  \
1                 12Z             0.0            90.0             0.0   
2                 12Z           315.0            45.0             0.0   
3                 ENZ            95.0             5.0             0.0   
4                 ENZ            90.0             0.0             0.0   
...               ...             ...             ...             ...   
5101562           ENZ            90.0             0.0             0.0   
5101563           ENZ           150.0            60.0             0.0   
5101564           12Z            41.0           131.0             0.0   
5101565           ENZ            90.0             0.0             0.0   
5101566           ENZ            90.0             0.0             0.0   

        source_type                source_origin_time  source_latitude   
0        earthquake  2013-07-23 00:23:14.260000+00:00         -63.2026  \
1        earthquake  2013-07-23 00:23:14.260000+00:00         -63.2026   
2        earthquake  2013-07-23 00:23:14.260000+00:00         -63.2026   
3        earthquake  2013-07-23 01:12:59.270000+00:00          60.7970   
4        earthquake  2013-07-23 01:12:59.270000+00:00          60.7970   
...             ...              

In [10]:
np_metadata = metadata.to_numpy()
print(np_metadata.shape)

all_phase_ids = np_metadata[:,1]
all_sta_lats = np_metadata[:,9]
all_sta_lons = np_metadata[:,10]
all_source_lats = np_metadata[:,18]
all_source_lons = np_metadata[:,19]
all_source_depthskm = np_metadata[:,20]

print(all_phase_ids)
print(all_sta_lats)
print(all_sta_lons)
print(all_source_lats)
print(all_source_lons)
print(all_source_depthskm)

(5101567, 56)
['usc000irgm_GE.SNAA.BH*.--_P' 'usc000irgm_IU.PMSA.BH*.10_Sn'
 'usc000irgm_IU.QSPA.BH*.10_P' ... 'us6000d4ny_IU.COLA.HH*.00_Pn'
 'us6000d4ny_TA.J18K.BH*.--_Pn' 'us6000d4ny_TA.M17K.BH*.--_Pn']
[-71.6707 -64.7744 -89.9289 ... 64.873599 63.465 61.4009]
[-2.8379 -64.0489 144.4382 ... -147.8616 -156.7154 -157.4375]
[-63.2026 -63.2026 -63.2026 ... 62.3568 62.3568 62.3568]
[-63.6217 -63.6217 -63.6217 ... -151.1274 -151.1274 -151.1274]
[10.0 10.0 10.0 ... 77.7 77.7 77.7]


In [13]:
print(valid_phase_id.shape)
print(train_phase_id.shape)

(489268,)
(2431341,)


In [29]:
print(all_phase_ids)
print(valid_phase_id)

['usc000irgm_GE.SNAA.BH*.--_P' 'usc000irgm_IU.PMSA.BH*.10_Sn'
 'usc000irgm_IU.QSPA.BH*.10_P' ... 'us6000d4ny_IU.COLA.HH*.00_Pn'
 'us6000d4ny_TA.J18K.BH*.--_Pn' 'us6000d4ny_TA.M17K.BH*.--_Pn']
[b'us1000h4vb_PR.AGPR.BH*.--_Pn' b'us1000h4vb_PR.OBIP.BH*.--_Pn'
 b'us1000h4vb_PR.PCDR.BH*.--_Pn' ... b'us7000709t_AU.MTN.BH*.00_P'
 b'us7000709t_G.DZM.BH*.00_Pn' b'us7000709t_G.SANVU.BH*.00_Pn']


In [47]:
new_valid_pids = []

for idx in range(len(valid_phase_id)):
#     print(valid_phase_id[idx])
#     print(valid_phase_id[idx].decode())
    new_valid_pids.append(valid_phase_id[idx].decode())
    
new_train_pids = []

for idx in range(len(train_phase_id)):
#     print(train_phase_id[idx])
#     print(train_phase_id[idx].decode())
    new_train_pids.append(train_phase_id[idx].decode())

In [49]:
len(new_valid_pids)

489268

In [50]:
len(new_train_pids)

2431341

In [54]:
def compare_arrays(arr1, arr2):
    return [i for i, x in enumerate(arr2) if x in arr1]

# Test of method

# print('Started test validation: ' + str(time.ctime()))
# valid_match_id_idxs = compare_arrays(new_valid_pids, all_phase_ids)
# print(len(valid_match_id_idxs))
# print(valid_match_id_idxs)
# np.savetxt('/home/sdybing/mlaapde/match_id_idxs_validdata.txt', valid_match_id_idxs)
# print('Finished validation: ' + str(time.ctime()))

print('Started validation: ' + str(time.ctime()))
valid_match_id_idxs = compare_arrays(new_valid_pids, all_phase_ids)
print(len(valid_match_id_idxs))
np.savetxt('/home/sdybing/mlaapde/match_id_idxs_validdata.txt', valid_match_id_idxs)
print('Finished validation: ' + str(time.ctime()))

print('Started training: ' + str(time.ctime()))
train_match_id_idxs = compare_arrays(new_train_pids, all_phase_ids) # started 6:pm
print(len(train_match_id_idxs))
np.savetxt('/home/sdybing/mlaapde/match_id_idxs_traindata.txt', train_match_id_idxs)
print('Finished training: ' + str(time.ctime()))

Started validation: Wed Sep 27 10:34:41 2023
489268
Finished validation: Wed Sep 27 21:20:25 2023
Started training: Wed Sep 27 21:20:25 2023
2431341
Finished training: Fri Sep 29 22:15:26 2023


In [55]:
train_match_id_idxs = np.loadtxt('/home/sdybing/mlaapde/match_id_idxs_traindata.txt')
train_idxs = train_match_id_idxs.astype(int)
print(train_idxs)

[  12001   12007   12008 ... 3813088 3813089 3813090]


In [57]:
train_phase_ids = all_phase_ids[train_idxs]
train_sta_lats = all_sta_lats[train_idxs]
train_sta_lons = all_sta_lons[train_idxs]
train_source_lats = all_source_lats[train_idxs]
train_source_lons = all_source_lons[train_idxs]
train_source_depthskm = all_source_depthskm[train_idxs]

print(train_phase_id)

print(train_phase_ids)
print(train_sta_lats)
print(train_sta_lons)
print(train_source_lats)
print(train_source_lons)
print(train_source_depthskm)

# np.array_equal(test_phase_id, test_phase_ids)

[b'usb000it1p_HL.ITM.HH*.--_P' b'usb000it1p_IM.MK31.BH*.--_P'
 b'usb000it1p_KZ.ABKAR.BH*.--_P' ... b'us1000h4te_TA.N17K.BH*.--_Pn'
 b'us1000h4te_TA.O14K.BH*.--_Pn' b'us1000h4te_TA.O16K.BH*.--_Pn']
['usb000it1p_HL.ITM.HH*.--_P' 'usb000it1p_IM.MK31.BH*.--_P'
 'usb000it1p_KZ.ABKAR.BH*.--_P' ... 'us1000h4te_TA.N17K.BH*.--_Pn'
 'us1000h4te_TA.O14K.BH*.--_Pn' 'us1000h4te_TA.O16K.BH*.--_Pn']
[37.178719 46.793682 49.2556 ... 60.5269 59.2533 59.5938]
[21.92522 82.290565 59.9431 ... -157.1867 -161.2638 -158.0932]
[32.58 32.58 32.58 ... 64.4041 64.4041 64.4041]
[48.44 48.44 48.44 ... -172.8239 -172.8239 -172.8239]
[16.3 16.3 16.3 ... 10.0 10.0 10.0]


In [60]:
# Make new array with test data columns

train_metadata = np.column_stack((train_phase_ids,train_sta_lats,train_sta_lons,train_source_lats,train_source_lons,train_source_depthskm))
print(train_metadata.shape)

print(train_metadata[0])
print(train_metadata[1])
print(train_metadata[-1])

# np.save('/home/sdybing/mlaapde/traindata_metadata_w_sourcestalocs.txt',)


(2431341, 6)
['usb000it1p_HL.ITM.HH*.--_P' 37.178719 21.92522 32.58 48.44 16.3]
['usb000it1p_IM.MK31.BH*.--_P' 46.793682 82.290565 32.58 48.44 16.3]
['us1000h4te_TA.O16K.BH*.--_Pn' 59.5938 -158.0932 64.4041 -172.8239 10.0]


In [61]:
from obspy.geodetics import gps2dist_azimuth, kilometer2degrees

dists_km = []
dists_deg = []

for idx in range(len(train_metadata)):
    
    phase_id = train_metadata[idx,0]
    sta_lat = train_metadata[idx,1]
    sta_lon = train_metadata[idx,2]
    source_lat = train_metadata[idx,3]
    source_lon = train_metadata[idx,4]
    
    distaz = gps2dist_azimuth(source_lat, source_lon, sta_lat, sta_lon)
    dist_m = distaz[0]
    dist_km = dist_m/1000
    dist_deg = kilometer2degrees(dist_km)
    dists_km.append(dist_km)
    dists_deg.append(dist_deg)
    
    if idx == 0:
        print(dists_km)
        print(dists_deg)
    
dists_km_arr = np.array(dists_km)
dists_deg_arr = np.array(dists_deg)

print(dists_km_arr.shape)
print(dists_deg_arr.shape)

[2468.5467817920335]
[22.200174560867257]
(2431341,)
(2431341,)


In [62]:
print(max(dists_km_arr))
print(max(dists_deg_arr))

11081.64550107228
99.65963228246399


In [63]:
train_metadata_hypdists = np.column_stack((train_metadata,dists_km_arr,dists_deg_arr))
print(train_metadata_hypdists.shape)
print(train_metadata_hypdists[0])

(2431341, 8)
['usb000it1p_HL.ITM.HH*.--_P' 37.178719 21.92522 32.58 48.44 16.3
 2468.5467817920335 22.200174560867257]


In [64]:
np.save('/home/sdybing/mlaapde/train_metadata_hypdists.npy', train_metadata_hypdists, allow_pickle = True)